<?php

// formlist array[];
return [
    [
        'name' => 'email',
        'section' => 'Camper',
        'title' => 'Email',
        'type' => 'email',
        'required' => true,
    ],
    [
        'name' => 'camper_name',
        'section' => 'Camper',
        'title' => 'Name',
        'type' => 'hidden',
    ],
    [
        'name' => 'camper_name_first',
        'section' => 'Camper',
        'title' => 'First Name',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
    ],
    [
        'name' => 'camper_name_last',
        'section' => 'Camper',
        'title' => 'Last Name',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
    ],
    [
        'name' => 'camper_name_middle',
        'section' => 'Camper',
        'title' => 'Middle Initial',
        'type' => 'text',
        'required' => true,
        'maxlength' => 1,
        'lettersonly' => true,
    ],
    [
        'name' => 'camper_birth_date',
        'section' => 'Camper',
        'title' => 'Birthday',
        'type' => 'date',
        'required' => true,
    ],
    [
        'name' => 'camper_age',
        'section' => 'Camper',
        'title' => 'Age',
        'type' => 'text',
        'required' => true,
        'number' => true,
        'readonly' => true,
        'style' => 'background-color: lightgray;border: 1px solid grey; width:50px;',
        'customrules' => [
            'min_age' => '/features/events/templates/camp_2025/custom.php',
            'max_age' => '/features/events/templates/camp_2025/custom.php',
        ],
    ],
    [
        'name' => 'camper_grade',
        'section' => 'Camper',
        'title' => 'Grade',
        'type' => 'text',
        'required' => true,
        'number' => true,
        'max' => 12,
        'min' => 1,
    ],
    [
        'name' => 'camper_gender',
        'section' => 'Camper',
        'title' => 'Gender',
        'type' => 'select',
        'options' => get_form_gender_options(),
        'required' => true,
    ],
    [
        'name' => 'camper_home_congregation',
        'section' => 'Camper',
        'title' => 'Congregation',
        'type' => 'text',
        'required' => false,
        'nonumbers' => true,
    ],
    [
        'name' => 'parent_name1',
        'section' => 'Parent',
        'title' => 'Parent/Guardian 1',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
    ],
    [
        'name' => 'parent_address_line1',
        'section' => 'Parent',
        'title' => 'Address 1',
        'type' => 'text',
        'required' => true,
    ],
    [
        'name' => 'parent_address_line2',
        'section' => 'Parent',
        'title' => 'Address 2',
        'type' => 'text',
        'required' => false,
    ],
    [
        'name' => 'parent_address_city',
        'section' => 'Parent',
        'title' => 'City',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
    ],
    [
        'name' => 'parent_address_state',
        'section' => 'Parent',
        'title' => 'State',
        'type' => 'select',
        'options' => get_form_USSTATES_options(),
        'required' => true,
    ],
    [
        'name' => 'parent_address_zipcode',
        'section' => 'Parent',
        'title' => 'Zipcode',
        'type' => 'text',
        'required' => true,
        'number' => true,
        'minlength' => 5,
    ],
    [
        'name' => 'parent_phone1',
        'section' => 'Parent',
        'title' => 'Phone 1',
        'type' => 'tel',
        'required' => true,
    ],
    [
        'name' => 'parent_phone2',
        'section' => 'Parent',
        'title' => 'Phone 2',
        'type' => 'tel',
        'required' => true,
    ],
    [
        'name' => 'parent_phone3',
        'section' => 'Parent',
        'title' => 'Phone 3',
        'type' => 'tel',
        'required' => false,
    ],
    [
        'name' => 'parent_phone4',
        'section' => 'Parent',
        'title' => 'Phone 4',
        'type' => 'tel',
        'required' => false,
    ],
    [
        'name' => 'consent',
        'section' => 'Health',
        'title' => 'CONSENT FOR MEDICAL TREATMENT OF A MINOR CHILD',
        'type' => 'html',
        'displayonly' => true,
        'file' => '/features/events/templates/camp_2025/consent.html',
    ],
    [
        'name' => 'health_member_name',
        'section' => 'Health',
        'title' => 'Member Name',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
    ],
    [
        'name' => 'health_relationship',
        'section' => 'Health',
        'title' => 'Relationship to Member',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
    ],
    [
        'name' => 'health_insurance',
        'section' => 'Health',
        'title' => 'Medical Insurance Carrier',
        'type' => 'text',
        'required' => true,
    ],
    [
        'name' => 'health_benefit_code',
        'section' => 'Health',
        'title' => 'Benefit Code',
        'type' => 'text',
        'required' => false,
    ],
    [
        'name' => 'health_account',
        'section' => 'Health',
        'title' => 'Account Number',
        'type' => 'text',
        'required' => false,
    ],
    [
        'name' => 'health_expiration',
        'section' => 'Health',
        'title' => 'Insurance Expiration',
        'type' => 'date',
        'required' => false,
    ],
    [
        'name' => 'health_history',
        'section' => 'Health',
        'title' => 'Medical History',
        'type' => 'textarea',
        'required' => false,
    ],
    [
        'name' => 'health_allergies',
        'section' => 'Health',
        'title' => 'Allergies',
        'type' => 'textarea',
        'required' => false,
    ],
    [
        'name' => 'health_existing',
        'section' => 'Health',
        'title' => 'Existing Conditions / Medical Issues',
        'type' => 'textarea',
        'required' => false,
    ],
    [
        'name' => 'health_medicines',
        'section' => 'Health',
        'title' => 'Medicines',
        'type' => 'textarea',
        'required' => false,
    ],
    [
        'name' => 'health_tetanus_date',
        'section' => 'Health',
        'title' => 'Last Tetanus Injection',
        'type' => 'date',
        'required' => false,
    ],
    [
        'name' => 'camper_picture',
        'section' => 'Pay',
        'title' => 'Camper Picture',
        'type' => 'select',
        'selected' => '0',
        'dynamicoptions' => [
            'picture' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'camper_shirt',
        'section' => 'Pay',
        'title' => 'Shirt',
        'type' => 'hidden',
        'dynamicvalue' => [
            'shirt' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'camper_shirt_size',
        'section' => 'Pay',
        'title' => 'Shirt Size',
        'type' => 'select',
        'dynamicoptions' => [
            'shirt' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'camper_shirt_price',
        'section' => 'Pay',
        'title' => 'Shirt Price',
        'type' => 'hidden',
        'dynamicvalue' => [
            'shirt_price' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'payment_method',
        'section' => 'Pay',
        'title' => 'Payment Method',
        'type' => 'select',
        'options' => [
            "" => "Choose One",
            "PayPal" => "PayPal",
            "Pay Later" => "Pay Later",
        ],
        'required' => true,
    ],
    [
        'name' => 'campership',
        'section' => 'Pay',
        'title' => 'Campership',
        'type' => 'hidden',
        'required' => false,
    ],
    [
        'name' => 'campershipcode',
        'section' => 'Pay',
        'title' => 'Apply Campership',
        'type' => 'custom',
        'customtype' => [
            'campershipsearch' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
        'displayonly' => true,
    ],
    [
        'name' => 'payment_note',
        'section' => 'Pay',
        'title' => 'Notes',
        'type' => 'custom',
        'customtype' => [
            'paymentnote' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
        'displayonly' => true,
    ],
    [
        'name' => 'total_owed',
        'section' => 'Pay',
        'title' => 'Amount Owed',
        'type' => 'hidden',
        'required' => false,
    ],
    [
        'name' => 'paid',
        'section' => 'Pay',
        'title' => 'Amount Paid',
        'type' => 'hidden',
        'required' => false,
    ],
];