<?php

// Include template specific functions.
include_once($CFG->dirroot . "/features/events/templates/camp_2025/lib.php");

// formlist array[];
return [
    [
        'name' => 'reglookup',
        'section' => 'Basic Camper Information',
        'title' => 'Prior Registrations',
        'type' => 'custom',
        'displayonly' => true,
        'customtype' => [
            'reglookup' => '/features/events/templates/camp_2025/custom.php',
        ],
    ],
    [
        'name' => 'email',
        'section' => 'Basic Camper Information',
        'title' => 'Email',
        'type' => 'email',
        'required' => true,
        'required_msg' => error_string('valid_req_email'),
        'help' => get_help("help_email:events:templates/camp_2025"),
        'dynamicvalue' => [
            'email' => '/features/events/templates/camp_2025/custom.php',
        ],
    ],
    [
        'name' => 'camper_birth_date',
        'section' => 'Basic Camper Information',
        'title' => 'Birthday',
        'type' => 'date',
        'required' => true,
        'help' => get_help("help_bday:events:templates/camp_2025"),
    ],
    [
        'name' => 'camper_age',
        'section' => 'Basic Camper Information',
        'title' => 'Age',
        'type' => 'text',
        'required' => true,
        'number' => true,
        'readonly' => true,
        'style' => 'background-color: lightgray;border: 1px solid grey; width:50px;',
        'customrules' => [
            'min_age' => '/features/events/templates/camp_2025/custom.php',
            'max_age' => '/features/events/templates/camp_2025/custom.php',
        ],
        'help' => get_help("help_age:events:templates/camp_2025"),
    ],
    [
        'name' => 'camper_name',
        'section' => 'Basic Camper Information',
        'title' => 'Name',
        'type' => 'hidden',
    ],
    [
        'name' => 'camper_name_first',
        'section' => 'Basic Camper Information',
        'title' => 'First Name',
        'type' => 'text',
        'required' => true,
        'required_msg' => error_string('valid_req_fname'),
        'nonumbers' => true,
        'autocapitalize' => 'words',
        'minlength' => 2,
        'help' => get_help("input_fname"),
    ],
    [
        'name' => 'camper_name_middle',
        'section' => 'Basic Camper Information',
        'title' => 'Middle Initial',
        'type' => 'text',
        'required' => true,
        'maxlength' => 1,
        'lettersonly' => true,
        'autocapitalize' => 'words',
        'help' => get_help("help_middlei:events:templates/camp_2025"),
    ],
    [
        'name' => 'camper_name_last',
        'section' => 'Basic Camper Information',
        'title' => 'Last Name',
        'type' => 'text',
        'required' => true,
        'required_msg' => error_string('valid_req_lname'),
        'nonumbers' => true,
        'autocapitalize' => 'words',
        'minlength' => 2,
        'help' => get_help("input_lname"),
    ],
    [
        'name' => 'camper_grade',
        'section' => 'Additional Camper Information',
        'title' => 'Grade',
        'type' => 'text',
        'required' => true,
        'number' => true,
        'max' => 12,
        'min' => 1,
        'help' => get_help("help_grade:events:templates/camp_2025"),
    ],
    [
        'name' => 'camper_gender',
        'section' => 'Additional Camper Information',
        'title' => 'Gender',
        'type' => 'select',
        'options' => TEMP_PROPS["GENDERS"],
        'required' => true,
        'help' => get_help("help_gender:events:templates/camp_2025"),
    ],
    [
        'name' => 'camper_home_congregation',
        'section' => 'Additional Camper Information',
        'title' => 'Congregation',
        'type' => 'text',
        'required' => false,
        'nonumbers' => true,
        'help' => get_help("help_congregation:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_name1',
        'section' => 'Contact Address',
        'title' => 'Parent/Guardian 1',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
        'help' => get_help("help_parent:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_address_line1',
        'section' => 'Contact Address',
        'title' => 'Address 1',
        'type' => 'text',
        'required' => true,
        'help' => get_help("help_address:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_address_line2',
        'section' => 'Contact Address',
        'title' => 'Address 2',
        'type' => 'text',
        'required' => false,
        'help' => get_help("help_address:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_address_city',
        'section' => 'Contact Address',
        'title' => 'City',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
        'help' => get_help("help_city:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_address_state',
        'section' => 'Contact Address',
        'title' => 'State',
        'type' => 'select',
        'options' => TEMP_PROPS["STATES"],
        'required' => true,
        'help' => get_help("help_state:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_address_zipcode',
        'section' => 'Contact Address',
        'title' => 'Zipcode',
        'type' => 'text',
        'required' => true,
        'number' => true,
        'minlength' => 5,
        'help' => get_help("help_zip:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_phone1',
        'section' => 'Contact by Phone',
        'title' => 'Phone 1',
        'type' => 'tel',
        'required' => true,
        'help' => get_help("help_phone:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_phone2',
        'section' => 'Contact by Phone',
        'title' => 'Phone 2',
        'type' => 'tel',
        'required' => true,
        'help' => get_help("help_phone:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_phone3',
        'section' => 'Contact by Phone',
        'title' => 'Phone 3',
        'type' => 'tel',
        'required' => false,
        'help' => get_help("help_phone:events:templates/camp_2025"),
    ],
    [
        'name' => 'parent_phone4',
        'section' => 'Contact by Phone',
        'title' => 'Phone 4',
        'type' => 'tel',
        'required' => false,
        'help' => get_help("help_phone:events:templates/camp_2025"),
    ],
    [
        'name' => 'consent',
        'section' => 'Required Health Information',
        'title' => 'CONSENT FOR MEDICAL TREATMENT OF A MINOR CHILD',
        'type' => 'html',
        'displayonly' => true,
        'file' => '/features/events/templates/camp_2025/consent.html',
    ],
    [
        'name' => 'health_member_name',
        'section' => 'Required Health Information',
        'title' => 'Member Name',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
        'help' => get_help("help_membername:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_relationship',
        'section' => 'Required Health Information',
        'title' => 'Relationship to Member',
        'type' => 'text',
        'required' => true,
        'nonumbers' => true,
        'help' => get_help("help_relationship:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_insurance',
        'section' => 'Required Health Information',
        'title' => 'Medical Insurance Carrier',
        'type' => 'text',
        'required' => true,
        'help' => get_help("help_carrier:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_account',
        'section' => 'Required Health Information',
        'title' => 'Account Number',
        'type' => 'text',
        'required' => true,
        'help' => get_help("help_memberid:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_expiration',
        'section' => 'Required Health Information',
        'title' => 'Insurance Expiration',
        'type' => 'date',
        'required' => true,
        'help' => get_help("help_healthto:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_benefit_code',
        'section' => 'Additional Health Information',
        'title' => 'Benefit Code',
        'type' => 'text',
        'required' => false,
        'help' => get_help("help_membercode:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_history',
        'section' => 'Additional Health Information',
        'title' => 'Medical History',
        'type' => 'textarea',
        'required' => false,
        'help' => get_help("help_history:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_allergies',
        'section' => 'Additional Health Information',
        'title' => 'Allergies',
        'type' => 'textarea',
        'required' => false,
        'help' => get_help("help_allergies:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_existing',
        'section' => 'Additional Health Information',
        'title' => 'Existing Conditions / Medical Issues',
        'type' => 'textarea',
        'required' => false,
        'help' => get_help("help_existing:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_medicines',
        'section' => 'Additional Health Information',
        'title' => 'Medicines',
        'type' => 'textarea',
        'required' => false,
        'help' => get_help("help_meds:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_tetanus_date',
        'section' => 'Additional Health Information',
        'title' => 'Last Tetanus Injection',
        'type' => 'date',
        'required' => false,
        'help' => get_help("help_tetanus:events:templates/camp_2025"),
    ],
    [
        'name' => 'health_consent_from',
        'section' => 'Additional Health Information',
        'title' => 'Health Conset Begins',
        'type' => 'hidden',
        'dynamicvalue' => [
            'health_consent_from' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'health_consent_to',
        'section' => 'Additional Health Information',
        'title' => 'Health Conset Ends',
        'type' => 'hidden',
        'dynamicvalue' => [
            'health_consent_to' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'camper_picture',
        'section' => 'Extras',
        'title' => 'Camper Picture',
        'type' => 'select',
        'selected' => '0',
        'dynamicoptions' => [
            'picture' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
        'dynamichelp' => [
            'picture' => '/features/events/templates/camp_2025/custom.php',
        ],
    ],
    [
        'name' => 'camper_shirt',
        'section' => 'Extras',
        'title' => 'Shirt',
        'type' => 'hidden',
        'dynamicvalue' => [
            'shirt' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'camper_shirt_size',
        'section' => 'Extras',
        'title' => 'Shirt Size',
        'type' => 'select',
        'dynamicoptions' => [
            'shirt' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => true,
        'dynamichelp' => [
            'shirt_size' => '/features/events/templates/camp_2025/custom.php',
        ],
    ],
    [
        'name' => 'camper_shirt_price',
        'section' => 'Extras',
        'title' => 'Shirt Price',
        'type' => 'hidden',
        'dynamicvalue' => [
            'shirt_price' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'camper_shirt_price',
        'section' => 'Extras',
        'title' => 'Shirt Price',
        'type' => 'hidden',
        'dynamicvalue' => [
            'shirt_price' => '/features/events/templates/camp_2025/custom.php',
        ],
        'required' => false,
    ],
    [
        'name' => 'payment_method',
        'section' => 'Checkout',
        'checkout' => true,
        'title' => 'Payment Method',
        'type' => 'select',
        'options' => [
            "" => "Choose One",
            "PayPal" => "PayPal",
            "Pay Later" => "Pay Later",
        ],
        'required' => true,
    ],
    [
        'name' => 'total_value',
        'section' => 'Checkout',
        'checkout' => true,
        'title' => 'Total Value',
        'type' => 'hidden',
        'required' => false,
    ],
    [
        'name' => 'total_owed',
        'section' => 'Checkout',
        'checkout' => true,
        'title' => 'Total Owed',
        'type' => 'hidden',
        'required' => false,
    ],
    [
        'name' => 'total_paid',
        'section' => 'Checkout',
        'checkout' => true,
        'title' => 'Total Paid',
        'type' => 'hidden',
        'required' => false,
    ],
    [
        'name' => 'campership',
        'section' => 'Checkout',
        'checkout' => true,
        'title' => 'Campership',
        'type' => 'hidden',
        'required' => false,
    ],
];